### ISSUE TITLE
Integration test for new RPCs added

### ISSUE THREAD

**Issue by jaiminsh** [googleapis/java-os-config#375]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
What you want to happen.
Would like more test cases to be added as a follow-up to #89 
Adding test for GetInventory, ListInventories, GetVulnerabilityReport and ListVulnerabilityReports. The tests should point to a zonal endpoint https://{zone}-osconfig.googleapis.com for them to work.

**Describe alternatives you've considered**
N/A

**Additional context**
I plan to use these integration tests as test cases for the service's VPC-SC integration, and would like each API in scope to have an associated test case

**Comment by lesv** [comment]
@jaiminsh If you are a Googler, please visit github/ and register. Also signup for **googleapis** org on the same site.

**Comment by suztomo** [comment]
Closing for obsolete.
